### ISSUE TITLE
Where is my Author-Page? ;)

### ISSUE THREAD

**Issue by oliveratgithub** [namics/SitecoreBlog#7]
Just kidding 😋

Nice to see some updates to the Namics Sitecore Blog! Almost „nostalgic“ for me already 😇

LG Oli

**Comment by NaibafCH** [comment]
Hey Oli 😃 

This is how you can create your own author page: https://github.com/namics/SitecoreBlog/tree/master/docs#how-to-create-your-own-author-page
Create a pull request and I'll merge it back 👍 

Cya

**Comment by oliveratgithub** [comment]
Thanks @NaibafCH – I‘ll look into it, for the sale of some fun 😊

Cheers

**Comment by oliveratgithub** [comment]
Thanks @NaibafCH 👍 [Looking good](https://sitecore.namics.com/authors/oraduner/) 😋
